[package]
name = "waysay"
version = "0.1.0"
authors = ["Josh Mcguigan"]
edition = "2018"

[dependencies]
smithay-client-toolkit = { git = "https://github.com/Smithay/client-toolkit" }
andrew = { git = "https://github.com/Smithay/andrew" }
byteorder = "1.3.4"
